### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message

### ISSUE THREAD

**Issue by musca1997** [OpenIB/OpenIB#293]
`PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message 'The "" directory does not exist.' in /var/www/OpenIB/inc/lib/Twig/Loader/Filesystem.php:93\nStack trace:\n#0 /var/www/OpenIB/inc/lib/Twig/Loader/Filesystem.php(75): Twig_Loader_Filesystem->addPath(NULL, '__main__')\n#1 /var/www/OpenIB/inc/template.php(23): Twig_Loader_Filesystem->setPaths(NULL)\n#2 /var/www/OpenIB/inc/template.php(42): load_twig()\n#3 /var/www/OpenIB/inc/display.php(115): Element('error.html', Array)\n#4 /var/www/OpenIB/inc/functions.php(351): error('Caught fatal er...', 3)\n#5 [internal function]: fatal_error_handler()\n#6 {main}\n  thrown in /var/www/OpenIB/inc/lib/Twig/Loader/Filesystem.php on line 93`

how can i solve this?

**Comment by musca1997** [comment]
this is the error_log when i try to access /mod.php page
